import * as Rx from 'rxjs';
import * as Rxo from 'rxjs/operators';
import { Service } from './service-resolver';
import { Album, ArtistData, Song, Spotlight } from '../types/types';

const blankData: ArtistData = {
  spotlight: { songIds: "[]" },
  songs: [],
  albums: []
}

const kraedtData: ArtistData = {
  spotlight: { songIds: "[52,51]" },
  songs: [
    {
      id: 0,
      downloadUrl: "Crate.mp3",
      title: "Crate",
      artist: "Kraedt",
      genre: "Electro House",
      imageUrl: "Crate.jpg",
      buyable: false,
      downloadable: true,
      youtubeId: "Ti8Z28fihyg",
      itunesUrl: "",
      beatportUrl: "",
      amazonUrl: "",
      spotifyUrl: "",
      licenseId: 1
    },
    {
      id: 1,
      downloadUrl: "Syntax.mp3",
      title: "Syntax",
      artist: "Kraedt",
      genre: "Electro House",
      imageUrl: "Syntax.jpg",
      buyable: true,
      downloadable: true,
      youtubeId: "GvJx6T3M64g",
      itunesUrl: "https://itunes.apple.com/us/album/the-record-crate/id1195366160",
      beatportUrl: "",
      amazonUrl: "https://www.amazon.com/Record-Crate-Kraedt/dp/B01MT9BKO0/ref=sr_1_3?s=dmusic&ie=UTF8&qid=1491041296&sr=1-3-mp3-albums-bar-strip-0&keywords=Kraedt",
      spotifyUrl: "https://open.spotify.com/album/5BHcEqyyuer5W8ikGztMJm",
      licenseId: 1
    },
    /*{
      id: 2,
      downloadUrl: "Lux.mp3",
      title: "Lux",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 3,
      downloadUrl: "Finite.mp3",
      title: "Finite",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 4,
      downloadUrl: "Facet.mp3",
      title: "Facet",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 5,
      downloadUrl: "Isometric.mp3",
      title: "Isometric",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 6,
      downloadUrl: "How I Roll (Kraedt Remix).mp3",
      title: "How I Roll (Kraedt Remix)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 7,
      downloadUrl: "Pyromania.mp3",
      title: "Pyromania",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 8,
      downloadUrl: "Levitate.mp3",
      title: "Levitate",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 9,
      downloadUrl: "Zero Gravity.mp3",
      title: "Zero Gravity",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 10,
      downloadUrl: "!",
      title: "Blackout",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 11,
      downloadUrl: "!",
      title: "Homebound",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 12,
      downloadUrl: "Heart Attack (Kraedt Remix).mp3",
      title: "Heart Attack (Kraedt Remix)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 13,
      downloadUrl: "Brink.mp3",
      title: "Brink",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 14,
      downloadUrl: "Boxcutter.mp3",
      title: "Boxcutter",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 15,
      downloadUrl: "Life At Balance (Kraedt Epic Trance Edit).mp3",
      title: "Life At Balance (Kraedt's Epic Trance Edit)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 16,
      downloadUrl: "Where Do We Go (Kraedt Remix).mp3",
      title: "Where Do We Go (Kraedt Remix)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 17,
      downloadUrl: "Get On Up (Kraedt Remix).mp3",
      title: "Get On Up (Kraedt Remix)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 18,
      downloadUrl: "Brink (VIP).mp3",
      title: "Brink (VIP)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 19,
      downloadUrl: "Lene.mp3",
      title: "Lene",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 20,
      downloadUrl: "Submersion.mp3",
      title: "Submersion",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 21,
      downloadUrl: "Loot.mp3",
      title: "Loot",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 22,
      downloadUrl: "!",
      title: "Find The Pieces (Kraedt Remix)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 23,
      downloadUrl: "Cloud Surfing.mp3",
      title: "Cloud Surfing",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 24,
      downloadUrl: "Emerald.mp3",
      title: "Emerald",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 25,
      downloadUrl: "!",
      title: "Insomnia",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 26,
      downloadUrl: "!",
      title: "Specter",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 27,
      downloadUrl: "Mystic.mp3",
      title: "Mystic",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 28,
      downloadUrl: "!",
      title: "You Can Find It",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 29,
      downloadUrl: "Storm Clouds.mp3",
      title: "Storm Clouds",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 30,
      downloadUrl: "Submersion (VIP).mp3",
      title: "Submersion (VIP)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 31,
      downloadUrl: "White Lies (Kraedt Remix).mp3",
      title: "White Lies (Kraedt Remix)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 32,
      downloadUrl: "Going Crazy.mp3",
      title: "Going Crazy",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 33,
      downloadUrl: "!",
      title: "What You Got",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 34,
      downloadUrl: "Till The Sun Comes Up (Kraedt Remix).mp3",
      title: "Till The Sun Comes Up (Kraedt Remix)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 35,
      downloadUrl: "Dimensions.mp3",
      title: "Dimensions",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 36,
      downloadUrl: "Jump Scare.mp3",
      title: "Jump Scare",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 37,
      downloadUrl: "!",
      title: "Rebound",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 38,
      downloadUrl: "Shape the Future.mp3",
      title: "Shape the Future",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 39,
      downloadUrl: "Surface.mp3",
      title: "Surface",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 40,
      downloadUrl: "Believe (Kraedt Remix).mp3",
      title: "Believe (Kraedt Remix)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 41,
      downloadUrl: "Hypnotized.mp3",
      title: "Hypnotized",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 42,
      downloadUrl: "Andromulus - True Potential (Kraedt Remix).mp3",
      title: "True Potential (Kraedt Remix)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 43,
      downloadUrl: "S3RL feat. Tamika - Tell Me What You Want (Kraedt Edit).mp3",
      title: "Tell Me What You Want (Kraedt Edit)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 44,
      downloadUrl: "S3RL feat. Tamika - Tell Me What You Want (Kraedt Edit Extended).mp3",
      title: "Tell Me What You Want (Kraedt Edit Extended)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 45,
      downloadUrl: "Kraedt - Come With Me.mp3",
      title: "Come With Me",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 46,
      downloadUrl: "!",
      title: "From the Dark",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 47,
      downloadUrl: "!",
      title: "From the Dark Instrumental",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 48,
      downloadUrl: "!",
      title: "Revenge (Kraedt Remix)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 49,
      downloadUrl: "Kraedt - Clockwork.mp3",
      title: "Clockwork",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 50,
      downloadUrl: "Kraedt - Bitwise.mp3",
      title: "Bitwise",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 51,
      downloadUrl: "Only One.mp3",
      title: "Only One",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 52,
      downloadUrl: "Horizon.mp3",
      title: "Horizon",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    },
    {
      id: 53,
      downloadUrl: "Horizon (Instrumental).mp3",
      title: "Horizon (Instrumental)",
      artist: null,
      genre: null,
      imageUrl: null,
      buyable: false,
      downloadable: false,
      youtubeId: null,
      itunesUrl: null,
      beatportUrl: null,
      amazonUrl: null,
      spotifyUrl: null,
      licenseId: 1
    }*/
  ],
  albums: [
  ]
}

const reloadSongs = new Rx.Subject();
const reloadAlbums = new Rx.Subject();
const reloadSpotlight = new Rx.Subject();

let instance: Service;

export default class MusicService implements Service {
  TypeName: string;
  Data = blankData;

  constructor() {
    this.TypeName = 'MusicService';

    if (!!instance) // todo: maybe find a workaround for this bs in the future?
      return;
    instance = this;
    const t = kraedtData;
    console.log(typeof t); // to shut it up for now
  }

  async FetchData(jsonFileUri: string) {
    jsonFileUri = 'https://www.googleapis.com/drive/v3/files/1UgSv7bkPNAbWP5yokSTd7FHlTyPivorL?alt=media';

    var setHeaders = new Headers();
    //setHeaders.append('Authorization', 'Bearer ' + authToken.access_token);
    setHeaders.append('Content-Type', 'json');

    var setOptions = {
      method: 'GET',
      headers: setHeaders,
      crossDomain: true
    };
    return await fetch(jsonFileUri, setOptions)
      .then(response => {
        if (response.ok) {
          var reader = response!.body!.getReader();
          var decoder = new TextDecoder();
          reader.read().then(function (result) {
            var data = {}
            data = decoder.decode(result.value, { stream: !result.done });
            console.log(data);
            return data;
          });
        }
        else {
          console.log(response);
          console.log("Response wast not ok");
        }
      }).catch(error => {
        console.log("There is an error " + error.message);
      });
  }

  Songs: Rx.Observable<Song[]> = Rx.EMPTY.pipe(
    Rxo.startWith(this.Data.songs),
    //Rx.mergeWith(reloadSongs),
    //ajaxGet('meta/songs'),
  )

  Albums: Rx.Observable<Album[]> = Rx.EMPTY.pipe(
    Rxo.startWith(this.Data.albums),
    //Rx.mergeWith(reloadAlbums),
    //ajaxGet('meta/albums'),
  )

  Spotlight: Rx.Observable<Spotlight> = Rx.EMPTY.pipe(
    Rxo.startWith(this.Data.spotlight),
    //Rx.mergeWith(reloadSpotlight),
    //ajaxGet('meta/spotlight'),
  )

  Intents = {
    ReloadSongs: reloadSongs,
    ReloadAlbums: reloadAlbums,
    ReloadSpotlight: reloadSpotlight
  }
}