import { ArtistData } from "./types/types";

export const kraedtData : ArtistData = {
  spotlight: { songIds: "[52,51]" },
  songs: [
    {
      "id": 0,
      "title": "Crate",
      "artist": "Kraedt",
      "genre": "Electro House",
      "imageUrl": "Crate.jpg",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "Ti8Z28fihyg",
      "licenseId": 1
    },
    {
      "id": 1,
      "title": "Syntax",
      "artist": "Kraedt",
      "genre": "Electro House",
      "imageUrl": "Syntax.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "GvJx6T3M64g",
      "itunesUrl": "https://itunes.apple.com/us/album/the-record-crate/id1195366160",
      "amazonUrl": "https://www.amazon.com/Record-Crate-Kraedt/dp/B01MT9BKO0/ref=sr_1_3?s=dmusic&ie=UTF8&qid=1491041296&sr=1-3-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/5BHcEqyyuer5W8ikGztMJm",
      "licenseId": 1
    },
    {
      "id": 2,
      "title": "Lux",
      "artist": "Kraedt",
      "genre": "Progressive House",
      "imageUrl": "Lux.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "MOWax_3ywrc",
      "itunesUrl": "https://itunes.apple.com/us/album/the-record-crate/id1195366160",
      "amazonUrl": "https://www.amazon.com/Record-Crate-Kraedt/dp/B01MT9BKO0/ref=sr_1_3?s=dmusic&ie=UTF8&qid=1491041296&sr=1-3-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/5BHcEqyyuer5W8ikGztMJm",
      "licenseId": 1
    },
    {
      "id": 3,
      "title": "Finite",
      "artist": "Kraedt",
      "genre": "Progressive House",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "fgGBR4JvMDs",
      "licenseId": 1
    },
    {
      "id": 4,
      "title": "Facet",
      "artist": "Kraedt & Rayzer",
      "genre": "Electro House",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "84dcsDRs8Ig",
      "licenseId": 1
    },
    {
      "id": 5,
      "title": "Isometric",
      "artist": "Kraedt",
      "genre": "Drum & Bass",
      "imageUrl": "Disco Dodgeball Soundtrack.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "ERRp_dPti-E",
      "itunesUrl": "https://itunes.apple.com/us/album/the-record-crate/id1195366160",
      "amazonUrl": "https://www.amazon.com/Record-Crate-Kraedt/dp/B01MT9BKO0/ref=sr_1_3?s=dmusic&ie=UTF8&qid=1491041296&sr=1-3-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/5BHcEqyyuer5W8ikGztMJm",
      "licenseId": 1
    },
    {
      "id": 6,
      "title": "How I Roll (Kraedt Remix)",
      "artist": "Savant",
      "genre": "Electro House",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "Gffg8u4Y_-4",
      "licenseId": 2
    },
    {
      "id": 7,
      "title": "Pyromania",
      "artist": "Kraedt",
      "genre": "Electro House",
      "imageUrl": "Pyromania.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "yO7vCM6288A",
      "itunesUrl": "https://itunes.apple.com/us/album/the-record-crate/id1195366160",
      "amazonUrl": "https://www.amazon.com/Record-Crate-Kraedt/dp/B01MT9BKO0/ref=sr_1_3?s=dmusic&ie=UTF8&qid=1491041296&sr=1-3-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/5BHcEqyyuer5W8ikGztMJm",
      "licenseId": 1
    },
    {
      "id": 8,
      "title": "Levitate",
      "artist": "Kraedt",
      "genre": "Progressive House",
      "imageUrl": "Levitate.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "Y4m4Qwsaqgw",
      "itunesUrl": "https://itunes.apple.com/us/album/the-record-crate/id1195366160",
      "amazonUrl": "https://www.amazon.com/Record-Crate-Kraedt/dp/B01MT9BKO0/ref=sr_1_3?s=dmusic&ie=UTF8&qid=1491041296&sr=1-3-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/5BHcEqyyuer5W8ikGztMJm",
      "licenseId": 1
    },
    {
      "id": 9,
      "title": "Zero Gravity",
      "artist": "Kraedt",
      "genre": "Big Room House",
      "imageUrl": "Zero Gravity.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "EyexbjAkcgg",
      "itunesUrl": "https://itunes.apple.com/us/album/the-record-crate/id1195366160",
      "amazonUrl": "https://www.amazon.com/Record-Crate-Kraedt/dp/B01MT9BKO0/ref=sr_1_3?s=dmusic&ie=UTF8&qid=1491041296&sr=1-3-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/5BHcEqyyuer5W8ikGztMJm",
      "licenseId": 1
    },
    {
      "id": 10,
      "title": "Blackout",
      "artist": "Kraedt",
      "genre": "Electro House",
      "imageUrl": "Blackout.jpg",
      "buyable": true,
      "downloadable": false,
      "youtubeId": "tUqMwMSu3Kw",
      "itunesUrl": "https://itunes.apple.com/us/album/blackout-single/id912126669",
      "beatportUrl": "https://www.beatport.com/release/blackout/1365624",
      "amazonUrl": "https://www.amazon.com/Blackout-Original-Mix/dp/B00NE6RPIW/ref=sr_1_23?s=dmusic&ie=UTF8&qid=1491041296&sr=1-23&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/3XrxsH3MrtCiJIqEpAY09G",
      "licenseId": 3
    },
    {
      "id": 11,
      "title": "Homebound",
      "artist": "Kraedt",
      "genre": "Drum & Bass",
      "imageUrl": "Homebound.jpg",
      "buyable": true,
      "downloadable": false,
      "youtubeId": "7CP9ZOHlF3Q",
      "itunesUrl": "https://itunes.apple.com/us/album/homebound-single/id928536735",
      "beatportUrl": "https://www.beatport.com/release/homebound/1397841",
      "amazonUrl": "https://www.amazon.com/Homebound-Original-Mix/dp/B00OD512SM/ref=sr_1_22?s=dmusic&ie=UTF8&qid=1491041296&sr=1-22&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/5Y8WF9Xk5AIblbp2EeMvsJ",
      "licenseId": 4
    },
    {
      "id": 12,
      "title": "Heart Attack (Kraedt Remix)",
      "artist": "Archie feat. Crywolf",
      "genre": "Melbourne Bounce",
      "imageUrl": "Heart Attack (Kraedt Remix).jpg",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "yn8MGDj6MIk",
      "licenseId": 2
    },
    {
      "id": 13,
      "title": "Brink",
      "artist": "Kraedt",
      "genre": "Complextro",
      "imageUrl": "Brink.jpg",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "AaCs6qJpohQ",
      "licenseId": 1
    },
    {
      "id": 14,
      "title": "Boxcutter (ft. Rayzer)",
      "artist": "Kraedt",
      "genre": "Electro House",
      "imageUrl": "Boxcutter.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "KMRAMqbVhpY",
      "itunesUrl": "https://itunes.apple.com/us/album/the-record-crate/id1195366160",
      "amazonUrl": "https://www.amazon.com/Record-Crate-Kraedt/dp/B01MT9BKO0/ref=sr_1_3?s=dmusic&ie=UTF8&qid=1491041296&sr=1-3-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/5BHcEqyyuer5W8ikGztMJm",
      "licenseId": 1
    },
    {
      "id": 15,
      "title": "Life At Balance (Kraedt's Epic Trance Edit)",
      "artist": "Jordan Maron vs Kraedt",
      "genre": "Trance",
      "imageUrl": "Life At Balance.jpg",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "8XzaILSakZg",
      "licenseId": 1
    },
    {
      "id": 16,
      "title": "Where Do We Go (Kraedt Remix)",
      "artist": "Ben Hennessy ft. 3PM",
      "genre": "Progressive House",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "JtU0T77RNVo",
      "licenseId": 2
    },
    {
      "id": 17,
      "title": "Get On Up (Kraedt Remix)",
      "artist": "Jauz x Pegboard Nerds",
      "genre": "Drumstep",
      "imageUrl": "Get On Up Remix.jpg",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "w2PKC0Cb-wg",
      "licenseId": 2
    },
    {
      "id": 18,
      "title": "Brink (VIP)",
      "artist": "Kraedt",
      "genre": "Dubstep",
      "imageUrl": "Brink VIP.jpg",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "BYMs0YQ8v1M",
      "licenseId": 1
    },
    {
      "id": 19,
      "title": "Lene",
      "artist": "Kraedt & Age Of Vinyl",
      "genre": "Progressive House",
      "imageUrl": "The Record Crate.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "jkKvq5lcBsE",
      "itunesUrl": "https://itunes.apple.com/us/album/the-record-crate/id1195366160",
      "amazonUrl": "https://www.amazon.com/Record-Crate-Kraedt/dp/B01MT9BKO0/ref=sr_1_3?s=dmusic&ie=UTF8&qid=1491041296&sr=1-3-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/5BHcEqyyuer5W8ikGztMJm",
      "licenseId": 1
    },
    {
      "id": 20,
      "title": "Submersion",
      "artist": "Kraedt",
      "genre": "Drum & Bass",
      "imageUrl": "Treasure EP.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "hQMlXFXJE_c",
      "itunesUrl": "https://itunes.apple.com/us/album/treasure-ep/id1192196861",
      "amazonUrl": "http://goo.gl/4OeFhE",
      "spotifyUrl": "https://open.spotify.com/album/3H4fAVBeAzXlx2wDMDNRC4",
      "licenseId": 1
    },
    {
      "id": 21,
      "title": "Loot",
      "artist": "Kraedt",
      "genre": "Glitch Hop",
      "imageUrl": "Treasure EP.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "yzgaQ5UGFTI",
      "itunesUrl": "https://itunes.apple.com/us/album/treasure-ep/id1192196861",
      "amazonUrl": "http://goo.gl/4OeFhE",
      "spotifyUrl": "https://open.spotify.com/album/3H4fAVBeAzXlx2wDMDNRC4",
      "licenseId": 1
    },
    {
      "id": 22,
      "title": "Find The Pieces (Kraedt Remix)",
      "artist": "Tryhardninja",
      "genre": "Dubstep",
      "imageUrl": "Find The Pieces Remix.jpg",
      "buyable": true,
      "downloadable": false,
      "youtubeId": "ifSwMU9m4Xk",
      "itunesUrl": "https://itunes.apple.com/us/album/find-pieces-kraedt-remix-single/id1103644041",
      "amazonUrl": "https://www.amazon.com/Find-the-Pieces-Kraedt-Remix/dp/B01EBCPMDM/ref=sr_1_1?s=dmusic&ie=UTF8&qid=1491048188&sr=1-1&keywords=Kraedt+find+the+pieces",
      "spotifyUrl": "https://open.spotify.com/album/1P1AWANSukRRjnofUk8O8V",
      "licenseId": 5
    },
    {
      "id": 23,
      "title": "Cloud Surfing",
      "artist": "Age Of Vinyl & Kraedt",
      "genre": "Drum & Bass",
      "imageUrl": "The Record Crate.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "lfHRXruoH1Q",
      "itunesUrl": "https://itunes.apple.com/us/album/the-record-crate/id1195366160",
      "amazonUrl": "https://www.amazon.com/Record-Crate-Kraedt/dp/B01MT9BKO0/ref=sr_1_3?s=dmusic&ie=UTF8&qid=1491041296&sr=1-3-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/5BHcEqyyuer5W8ikGztMJm",
      "licenseId": 1
    },
    {
      "id": 24,
      "title": "Emerald",
      "artist": "Kraedt",
      "genre": "Progressive House",
      "imageUrl": "The Record Crate.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "vzEwHEGzjoA",
      "itunesUrl": "https://itunes.apple.com/us/album/the-record-crate/id1195366160",
      "amazonUrl": "https://www.amazon.com/Record-Crate-Kraedt/dp/B01MT9BKO0/ref=sr_1_3?s=dmusic&ie=UTF8&qid=1491041296&sr=1-3-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/5BHcEqyyuer5W8ikGztMJm",
      "licenseId": 1
    },
    {
      "id": 25,
      "title": "Insomnia",
      "artist": "Kraedt",
      "genre": "Drum & Bass",
      "imageUrl": "Insomnia.jpg",
      "buyable": true,
      "downloadable": false,
      "youtubeId": "alFf6SK0H-Y",
      "itunesUrl": "https://itunes.apple.com/us/album/insomnia-single/id979956296",
      "beatportUrl": "https://www.beatport.com/release/insomnia/1501755",
      "amazonUrl": "https://www.amazon.com/Insomnia-Original-Mix/dp/B00V89C7QW/ref=sr_1_20?s=dmusic&ie=UTF8&qid=1491041296&sr=1-20&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/6PKmwO3bqyDazi0XsG0b3k",
      "licenseId": 3
    },
    {
      "id": 26,
      "title": "Specter",
      "artist": "Kraedt",
      "genre": "Progressive House",
      "imageUrl": "Specter.jpg",
      "buyable": true,
      "downloadable": false,
      "youtubeId": "fRzkhFA0wf8",
      "itunesUrl": "https://itunes.apple.com/us/album/specter-single/id1059553845",
      "beatportUrl": "https://www.beatport.com/release/specter/1654120",
      "amazonUrl": "https://www.amazon.com/Specter-Original/dp/B0180TUD68/ref=sr_1_19?s=dmusic&ie=UTF8&qid=1491041296&sr=1-19&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/0cf03N9ta2XdVpHM4bxiwG",
      "licenseId": 4
    },
    {
      "id": 27,
      "title": "Mystic",
      "artist": "Kraedt",
      "genre": "Progressive House",
      "imageUrl": "The Record Crate.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "0j_sVnPNsNg",
      "itunesUrl": "https://itunes.apple.com/us/album/the-record-crate/id1195366160",
      "amazonUrl": "https://www.amazon.com/Record-Crate-Kraedt/dp/B01MT9BKO0/ref=sr_1_3?s=dmusic&ie=UTF8&qid=1491041296&sr=1-3-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/5BHcEqyyuer5W8ikGztMJm",
      "licenseId": 1
    },
    {
      "id": 28,
      "title": "You Can Find It",
      "artist": "Tryhardninja & Kraedt",
      "genre": "Future Bass",
      "imageUrl": "You Can Find It.jpg",
      "buyable": true,
      "downloadable": false,
      "youtubeId": "dNo5EqVfaiA",
      "itunesUrl": "https://itunes.apple.com/us/album/you-can-find-it-single/id1204587589",
      "amazonUrl": "https://goo.gl/e0r7D2",
      "spotifyUrl": "https://open.spotify.com/album/0S3w9PKDn2isuU6Mkskb9l",
      "licenseId": 5
    },
    {
      "id": 29,
      "title": "Storm Clouds",
      "artist": "Kraedt",
      "genre": "Drum & Bass",
      "imageUrl": "Storm Clouds.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "tVQpAVgV4iI",
      "itunesUrl": "https://itunes.apple.com/us/album/storm-clouds-single/id1224863024",
      "amazonUrl": "https://www.amazon.com/dp/B06Y4FGWSM/ref=sr_1_10?ie=UTF8&qid=1491693100&sr=8-10&keywords=kraedt",
      "spotifyUrl": "https://open.spotify.com/album/77IFKdJR0SGgArSRQ8T4vZ",
      "licenseId": 1
    },
    {
      "id": 30,
      "title": "Submersion (VIP)",
      "artist": "Kraedt",
      "genre": "Drum & Bass",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "CD2h8r4HrSg",
      "licenseId": 1
    },
    {
      "id": 31,
      "title": "White Lies (Kraedt Remix)",
      "artist": "Vicetone ft. Chloe Angelides",
      "genre": "Dubstep",
      "imageUrl": "White Lies Remix.jpg",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "uKAZKZEFt4U",
      "licenseId": 2
    },
    {
      "id": 32,
      "title": "Going Crazy",
      "artist": "Kraedt",
      "genre": "Progressive House",
      "imageUrl": "GoingCrazy.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "pjaHEgIlYhg",
      "itunesUrl": "https://itunes.apple.com/us/album/going-crazy-single/id1281624414",
      "amazonUrl": "https://www.amazon.com/dp/B075M3ZQ26/",
      "spotifyUrl": "https://open.spotify.com/album/5IApdb0j12P0zKvkFze6Dk",
      "licenseId": 7
    },
    {
      "id": 33,
      "title": "What You Got",
      "artist": "Third Digit & Kraedt",
      "genre": "House Hybrid",
      "imageUrl": "What You Got.jpg",
      "buyable": true,
      "downloadable": false,
      "youtubeId": "TQLNN4loCdY",
      "itunesUrl": "https://itunes.apple.com/us/album/what-you-got-single/id1279566158",
      "amazonUrl": "https://www.amazon.com/What-You-Third-Digit-Kraedt/dp/B075DQVJR4/",
      "spotifyUrl": "https://open.spotify.com/album/0M1Bib0ww82etaysdLGM3i",
      "licenseId": 3
    },
    {
      "id": 34,
      "title": "Till The Sun Comes Up (Kraedt Remix)",
      "artist": "Firebeatz ft. Vertel",
      "genre": "Drum & Bass",
      "imageUrl": "TTSCU Remix.jpg",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "BkpaJlMneX8",
      "licenseId": 2
    },
    {
      "id": 35,
      "title": "Dimensions",
      "artist": "Kraedt",
      "genre": "Complextro",
      "imageUrl": "Dimensions.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "LnWrQoymtk0",
      "itunesUrl": "https://itunes.apple.com/us/album/dimensions-single/id1294048420",
      "amazonUrl": "https://www.amazon.com/Dimensions-Kraedt/dp/B0768Q13GQ/ref=sr_1_1?s=dmusic&ie=UTF8&qid=1507958475&sr=1-1-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/track/3cyMmq1fIUNwlEN8Bhn0CA",
      "licenseId": 1
    },
    {
      "id": 36,
      "title": "Jump Scare",
      "artist": "Kraedt",
      "genre": "Dubstep",
      "imageUrl": "Jump Scare.jpg",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "TZSff1mo5FU",
      "spotifyUrl": "https://open.spotify.com/album/0WubcHMnI7samSWDjZqg3n",
      "licenseId": 1
    },
    {
      "id": 37,
      "title": "Rebound",
      "artist": "Kraedt",
      "genre": "Glitch Hop",
      "imageUrl": "Rebound.jpg",
      "buyable": true,
      "downloadable": false,
      "youtubeId": "L2BmpQN3lFA",
      "itunesUrl": "https://itunes.apple.com/us/album/rebound-single/1294883030",
      "beatportUrl": "https://www.beatport.com/release/rebound/2132237",
      "amazonUrl": "https://www.amazon.com/Rebound-Kraedt/dp/B076CL2FY7/ref=sr_1_2?s=dmusic&ie=UTF8&qid=1510610757&sr=1-2-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/2ytNX7ylDGKY0xt2yvfBUA",
      "licenseId": 3
    },
    {
      "id": 38,
      "title": "Shape the Future",
      "artist": "Kraedt",
      "genre": "Drum & Bass",
      "imageUrl": "STF EP.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "sGy9HslW4Q0",
      "itunesUrl": "https://itunes.apple.com/us/album/shape-the-future-surface-single/1351123893",
      "amazonUrl": "https://www.amazon.com/Shape-Future-Surface-Kraedt/dp/B079YNMBTB/ref=sr_1_2?s=dmusic&ie=UTF8&qid=1519396578&sr=1-2-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/2YcWpOBpq9nzoFVsBTJnrP?si=JsdN-Iq4SNK-DhCF0x3LdA",
      "licenseId": 1
    },
    {
      "id": 39,
      "title": "Surface",
      "artist": "Kraedt",
      "genre": "Drum & Bass",
      "imageUrl": "STF EP.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "f6jDHtF6rOI",
      "itunesUrl": "https://itunes.apple.com/us/album/shape-the-future-surface-single/1351123893",
      "amazonUrl": "https://www.amazon.com/Shape-Future-Surface-Kraedt/dp/B079YNMBTB/ref=sr_1_2?s=dmusic&ie=UTF8&qid=1519396578&sr=1-2-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/2YcWpOBpq9nzoFVsBTJnrP?si=JsdN-Iq4SNK-DhCF0x3LdA",
      "licenseId": 1
    },
    {
      "id": 40,
      "title": "Believe (Kraedt Remix)",
      "artist": "Nitro Fun & Desso feat. Brenton Mattheus",
      "genre": "Electro House",
      "imageUrl": "Believe Remix.jpg",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "jlS6EZ1CF8s",
      "licenseId": 4
    },
    {
      "id": 41,
      "title": "Hypnotized",
      "artist": "Kraedt",
      "genre": "Drum & Bass",
      "imageUrl": "hypnotized.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "1d3K0xipSNg",
      "itunesUrl": "https://itunes.apple.com/us/album/hypnotized-single/1425296928",
      "amazonUrl": "https://www.amazon.com/Hypnotized-Kraedt/dp/B07GC8SLPZ/ref=sr_1_2?s=dmusic&ie=UTF8&qid=1535112050&sr=1-2-mp3-albums-bar-strip-0&keywords=Kraedt",
      "spotifyUrl": "https://open.spotify.com/album/0XwgZGOb5Mc3oiCMvOSmeO?si=OlILlj2IR2-8InagvldM-Q",
      "licenseId": 1
    },
    {
      "id": 42,
      "title": "True Potential (Kraedt Remix)",
      "artist": "Andromulus",
      "genre": "Trap / DnB",
      "imageUrl": "True Potential Remix.jpg",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "qjC5ru-VRyI",
      "licenseId": 2
    },
    {
      "id": 43,
      "title": "Tell Me What You Want (Kraedt Edit)",
      "artist": "S3RL feat. Tamika",
      "genre": "Melbourne Bounce",
      "imageUrl": "Tell Me What You Want Kraedt Edit.jpg",
      "buyable": false,
      "downloadable": true,
      "youtubeId": "rivMTT4pNMA",
      "licenseId": 2
    },
    {
      "id": 44,
      "title": "Tell Me What You Want (Kraedt Edit Extended)",
      "artist": "S3RL feat. Tamika",
      "genre": "Melbourne Bounce",
      "imageUrl": "Tell Me What You Want Kraedt Edit.jpg",
      "buyable": false,
      "downloadable": true,
      "licenseId": 2
    },
    {
      "id": 45,
      "title": "Come With Me",
      "artist": "Kraedt",
      "genre": "Progressive House",
      "imageUrl": "Come With Me.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "X6lkcOUvR1g",
      "itunesUrl": "https://itunes.apple.com/us/album/come-with-me-single/1459029149",
      "amazonUrl": "https://www.amazon.com/Come-Me-Kraedt/dp/B07QCKQVVS/",
      "spotifyUrl": "https://open.spotify.com/album/5aTX7v8b0RXQjPThrw3NFS?si=LKWg6rrKTwS_9QRh2E0vNQ",
      "licenseId": 1
    },
    {
      "id": 46,
      "title": "From the Dark",
      "artist": "TryHardNinja & Kraedt (feat. Lollia)",
      "genre": "Progressive House",
      "imageUrl": "From the Dark.jpg",
      "buyable": true,
      "downloadable": false,
      "youtubeId": "OzDwRBMPJUE",
      "itunesUrl": "https://itunes.apple.com/us/album/from-the-dark-single/1462247406",
      "amazonUrl": "https://www.amazon.com/Dark-feat-Kraedt-Lollia/dp/B07R6YS4Q2",
      "spotifyUrl": "https://open.spotify.com/album/6DJa3tuyG9Ly4jfYSheRod",
      "licenseId": 5
    },
    {
      "id": 48,
      "title": "Revenge (Kraedt Remix)",
      "artist": "Tryhardninja & CaptainSparklez",
      "genre": "Complextro",
      "imageUrl": "Revenge-Kraedt-Remix.jpg",
      "buyable": true,
      "downloadable": false,
      "youtubeId": "6HSzse0s2KU",
      "itunesUrl": "https://music.apple.com/us/album/revenge-feat-captainsparklez-kraedt-remix-single/1476407564",
      "amazonUrl": "https://www.amazon.com/Revenge-feat-CaptainSparklez-Kraedt-Remix/dp/B07WFHR3GH",
      "spotifyUrl": "https://open.spotify.com/album/59dHFz1u8C1mkcM1sGPhHq?si=NqjGIJR2R9-XhCRR7lRSsA",
      "licenseId": 5
    },
    {
      "id": 49,
      "title": "Clockwork",
      "artist": "Kraedt",
      "genre": "Dubstep / DnB",
      "imageUrl": "Clockwork.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "08uQPeXTLZM",
      "itunesUrl": "https://music.apple.com/us/album/clockwork-single/1500103259",
      "amazonUrl": "https://www.amazon.com/Clockwork-Kraedt/dp/B0851XZP8F/ref=sr_1_1",
      "spotifyUrl": "https://open.spotify.com/album/5j4WVQOaWcooZJTgG1fvxg",
      "licenseId": 1
    },
    {
      "id": 50,
      "title": "Bitwise",
      "artist": "Kraedt",
      "genre": "Electro Trance",
      "imageUrl": "Clockwork.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "dFhjEZOB3BE",
      "itunesUrl": "https://music.apple.com/us/album/clockwork-single/1500103259",
      "amazonUrl": "https://www.amazon.com/Clockwork-Kraedt/dp/B0851XZP8F/ref=sr_1_1",
      "spotifyUrl": "https://open.spotify.com/album/5j4WVQOaWcooZJTgG1fvxg",
      "licenseId": 1
    },
    {
      "id": 51,
      "title": "Only One",
      "artist": "Kraedt",
      "genre": "Progressive House",
      "imageUrl": "only one art.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "EXu9kBwutro",
      "itunesUrl": "https://music.apple.com/us/album/only-one-single/1572200120",
      "amazonUrl": "https://www.amazon.com/Only-One-Kraedt/dp/B0976DGYR6/ref=sr_1_3?dchild=1",
      "spotifyUrl": "https://open.spotify.com/album/0D1FxjtviOA2CAAiGQ3cwz?si=2ddc61a9719048d2",
      "licenseId": 1
    },
    {
      "id": 52,
      "title": "Horizon",
      "artist": "Kraedt",
      "genre": "Drum & Bass",
      "imageUrl": "horizon_art.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "ANcO_W3nhak",
      "itunesUrl": "https://music.apple.com/us/album/horizon-single/1582263965",
      "spotifyUrl": "https://open.spotify.com/album/1v7emQ18QeL42hg1RGJ5Y0",
      "licenseId": 1
    },
    {
      "id": 53,
      "title": "Horizon (Instrumental)",
      "artist": "Kraedt",
      "genre": "Drum & Bass",
      "imageUrl": "horizon_art.jpg",
      "buyable": true,
      "downloadable": true,
      "youtubeId": "ANcO_W3nhak",
      "itunesUrl": "https://music.apple.com/us/album/horizon-single/1582263965",
      "spotifyUrl": "https://open.spotify.com/album/1v7emQ18QeL42hg1RGJ5Y0",
      "licenseId": 1
    }
  ],
  albums: []
}